### ISSUE TITLE
Importing Collection Error That Wasn't Created On Zeromint Website

### ISSUE THREAD

**Issue by wwitkdqsck** [zeromintapp/community#16]
Hello @treeder @r-gochain ,i'm having problem Importing a Collection 

Error : Collections needs a description.

Contract Address :[0xF85A3e31a88430606aDAa96007A02b464799DF73](https://explorer.gochain.io/token/0xF85A3e31a88430606aDAa96007A02b464799DF73?addr_tab=transactions)
![ImportGoSinoContractError](https://user-images.githubusercontent.com/93308499/152362707-2669ca34-20a5-4510-9237-3d63ee7ca8a6.png)

Any Suggestions ?

**Comment by treeder** [comment]
Try the new URL import: https://zeromint.com/nfts/go/0xF85A3e31a88430606aDAa96007A02b464799DF73/1

**Comment by wwitkdqsck** [comment]
Okay 👌 thanks Travel for the Solution! will do it soon!

**Comment by wwitkdqsck** [comment]
> Try the new URL import: https://zeromint.com/nfts/go/0xF85A3e31a88430606aDAa96007A02b464799DF73/1

Okay it Works ..So @treeder the New Structure ,nobody Owns the Collections?How do i sell it ? and Make Changes to the Collection?Apprently its not in my User Collections Section .

**Comment by treeder** [comment]
If it wasn't created on Zeromint, then you'd have to make changes outside of Zeromint as well. You will be able to buy and sell them on Zeromint though.

**Comment by wwitkdqsck** [comment]
Hello @treeder @r-gochain ,For the NEW Import Url -> Will it be on the Same Url as the previous page [Import existing NFTs](https://zeromint.com/collections/import)?Or there will be a New URL soon? Because i only see (GoChain and Ethereum)

**Comment by treeder** [comment]
Just enter the URL in your browser:

```
https://zeromint.com/nfts/CHAIN/CONTRACT_ADDRESS/TOKEN_ID
```

**Comment by wwitkdqsck** [comment]
> Just enter the URL in your browser:
> 
> ```
> https://zeromint.com/nfts/CHAIN/CONTRACT_ADDRESS/TOKEN_ID
> ```

Thanks For The Input ,So there will be no direct Link On Zeromint Website To Import For Other Chain ?How Do i Edit The Collection? And Why im still unable to Set the price ? maybe because its Ur Collection Now? because you imported it first...

**Comment by gobullsclub** [comment]
Hi @treeder @r-gochain  will i have problem with My Collection Imported Previously ? Both Work or From Now on only the NEW URL will work ?I notice there is some error on the Explorer and Zeromint Website -> I'm asking because there will be a NFT GIveaway on my Twitter Page Very Soon, Don't want people to complain that they can't see their NFTs ...And 3 NFTs Bought already and its the same person. So please confirm So i can Refund the $GO to the Owner and Do it again with the NEW URL.
![GoBullsZeromintError-1](https://user-images.githubusercontent.com/97951436/152925429-d4d9a26a-276e-49f9-9d7d-c80e7e6af117.png)

**Comment by gobullsclub** [comment]
I Think It Was a Cache Problem,Seem to be working now!

**Comment by treeder** [comment]
It's pinata, they don't seem to be a very good host for your images, I always get rate limit errors on your collections from pinatacloud.com. I'd recommend using a different IPFS host like Cloudflare or something. You can use Pinata to pin your files, but use a different IPFS gateway.

**Comment by wwitkdqsck** [comment]
Thanks for the Tips! @treeder  i'll use cloudflare from now on! (But Pin on Pinata)!
