### ISSUE TITLE
Transfering NFT Error That Wasn't Created On Zeromint And On a Different Chain

### ISSUE THREAD

**Issue by gobullsclub** [zeromintapp/community#18]
Hello @treeder @r-gochain Any Suggestions?
I have problems transfering the NFTs from a different Chain.

Error = erc721.TransferFrom Failed :failed to estimate gas needed :insufficient funds for transfer
i tried adding more $GO didnt work

its from KCC Network (So KCS is needed for gas,or else it will fail)
You need to Buy KCS and store it in the Main Zeromint Wallet that controls the Fees
![TransferErrorOtherChain](https://user-images.githubusercontent.com/97951436/153894649-95dd0e17-188f-4da0-bac0-f9a73e56bc29.png)
![TransferErrorOtherChain2](https://user-images.githubusercontent.com/97951436/153894654-55d479b1-ecc8-4189-be16-4051b3815a81.png)

**Comment by treeder** [comment]
So it worked when you added KCS?

**Comment by gobullsclub** [comment]
Haven't tried that yet, but when I transferred from my metamask wallet to
Zeromint wallet , the network was KCC NOT GoChain.
I'll try later by adding some KCS on my Zeromint Wallet Address. Will
Update Soon! Thanks for replying!

**Comment by gobullsclub** [comment]
I tried adding a small amount of KCS in the Zeromint wallet address, got a different error.. 
![XRecorder_Edited_15022022_014636](https://user-images.githubusercontent.com/97951436/153918797-5e3ade99-7841-4b72-8e35-aa8aaec20e86.jpg)

**Comment by gobullsclub** [comment]
Hello @treeder @r-gochain i Tried Searching For answers ,maybe this is the solution? [Link](https://ethereum.stackexchange.com/questions/94412/valueerror-code-32000-message-only-replay-protected-eip-155-transac) Any Advice ?


Chain Name: KCC-MAINNET
Chain ID: 321
Symbol: KCS
RPC URL: https://rpc-mainnet.kcc.network
Explorer URL: https://explorer.kcc.io/en

**Comment by gobullsclub** [comment]
hello @r-gochain any updates on this ?because i need to Transfer Out the NFTs before the NFT marketplace Launch on MojitoSwap

**Comment by gobullsclub** [comment]
hello @r-gochain what about this problem,any solution?

**Comment by gobullsclub** [comment]
Hello  @treeder @r-gochain Should We close this issue? since we are moving Fully  towards Metamask (Like Opensea) ?

**Comment by treeder** [comment]
Nobody said fully that direction, just another option. Can you try it again though, I think some changes were rolled out to address this.

**Comment by gobullsclub** [comment]
Noted, tried again.. Got this error instead. Any Suggestions Travis? On my Zeromint Address there is 0.005 kcs just to let you know... 
![XRecorder_Edited_26022022_004734](https://user-images.githubusercontent.com/97951436/155754732-ebc7bdfd-cf83-4d43-a0c3-4550050df43a.jpg)

**Comment by gobullsclub** [comment]
Hello Guys ,@treeder  @r-gochain ,So by looking at the Error ,it seems That Zeromint does'nt Support  [KCC Network](https://kcc.io) ($KCS) ?But I Asked You Before ,You Guys Said Every Netwok That is Compatible With EVM can be Imported?
Please Advice 
Thanks

**Comment by treeder** [comment]
Alright, this should be working in about 5 minutes.

**Comment by gobullsclub** [comment]
Worked out great  without any issues! Thanks Guys  @treeder @r-gochain !

**Comment by gobullsclub** [comment]
👍
